# Generated by Django 3.1.1 on 2020-10-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201004_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logged_in',
            field=models.TextField(),
        ),
    ]
