# Generated by Django 3.1.1 on 2020-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201004_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
