# Generated by Django 3.1.1 on 2020-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201004_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_video',
            new_name='product_link',
        ),
        migrations.AddField(
            model_name='product',
            name='product_download',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
