# Generated by Django 3.1.1 on 2020-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201005_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
