# Generated by Django 3.1.1 on 2020-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201006_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
