# Generated by Django 3.1.1 on 2020-11-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201006_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getting_Started_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Getting_Started_Affiliate_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Affiliate_Link', models.CharField(blank=True, max_length=500, null=True)),
                ('Section_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.getting_started_section')),
            ],
        ),
    ]
