# Generated by Django 3.1.1 on 2020-11-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_model_content_affiliate_link_model_content_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_content_affiliate_link',
            name='Section_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.model_content_section'),
        ),
    ]
