# Generated by Django 3.1.1 on 2020-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201108_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getting_started_affiliate_link',
            name='Affiliate_Link',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='getting_started_section',
            name='Section',
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name='model_content_affiliate_link',
            name='Affiliate_Link',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='model_content_section',
            name='Section',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
