# Generated by Django 3.1.1 on 2020-11-08 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201108_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize_Content_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publish_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=350, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publish_Affiliate_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Affiliate_Link', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('Section_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.publish_section')),
            ],
        ),
        migrations.CreateModel(
            name='Customize_Content_Affiliate_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Affiliate_Link', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('Section_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customize_content_section')),
            ],
        ),
    ]
