# Generated by Django 3.1.1 on 2020-11-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_resources_affiliate_link_resources_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='getting_started_affiliate_link',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
