# Generated by Django 3.1.1 on 2020-11-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_getting_started_affiliate_link_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getting_started_affiliate_link',
            old_name='display_name',
            new_name='display_Name',
        ),
    ]
