# Generated by Django 3.1.1 on 2020-11-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20201111_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_content_affiliate_link',
            name='Display_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='getting_started_affiliate_link',
            name='Display_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publish_affiliate_link',
            name='Display_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resources_affiliate_link',
            name='Display_Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
